config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  get 'sessions/new'
  root 'tasks#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :tasks do
    collection do
      post :confirm
    end
  end
  resources :labels
  resources :labelilingss
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :labellings, dependent: :destroy
    has_many :labels, through: :labellings
    validates :title, presence: true
    validates :content, presence: true
    enum status: { 未着手: "未着手", 着手中: "着手中", 完了: "完了" }
    enum priority: { 高: 3, 中: 2, 低: 1 }
    scope :title_search, -> (title){where('title LIKE ?', "%#{title}%")}
    scope :status_search, -> (status){where('status LIKE ?', "#{status}")}
    scope :label_search, -> (label_ids){where(id: Labelling.where(label_id: label_ids).pluck(:task_id))}
    paginates_per 10
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  before_validation { email.downcase! }
  validates :name, length: { maximum: 30 }
  validates :email, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  has_secure_password
  before_destroy :admin_cannot_delete

  private
  
  def admin_cannot_delete
    throw :abort if User.exists?(admin: true) && self.admin == true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.select(:id, :name, :email, :admin, :created_at, :updated_at)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to tasks_path, notice: "管理者以外はアクセスできません" unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :require_admin

  def index
    @labels = Label.select(:name)
  end

  def show
    @label = Label.find(params[:id])
  end

  def new
    @label = Label.new
  end

  def edit
    @label = Label.find(params[:id])
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path(@label), notice: "ラベル「#{@label.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @label = Label.find(params[:id])
    if @label.update(label_params)
      redirect_to labels_path(@label), notice: "ラベル「#{@label.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path, notice: "ラベル「#{@label.name}」を削除しました。"
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end

  def require_admin
    redirect_to tasks_path, notice: "管理者以外はアクセスできません" unless current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if params[:task].present?
      title = params[:task][:title]
      status = params[:task][:status]
      label = params[:task][:label_id]
      if title.present? && status.present?
        @tasks = current_user.tasks.title_search(title).status_search(status).page(params[:page])
      elsif title.present? && status.blank?
        @tasks = current_user.tasks.title_search(title).page(params[:page])
      elsif label.present?
        @tasks = current_user.tasks.label_search(label).page(params[:page])
      else
        @tasks = current_user.tasks.status_search(status).page(params[:page])
      end
    elsif params[:sort_expired]
      @tasks = current_user.tasks.order(expired_at: :desc).page(params[:page])
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :desc).page(params[:page])
    else
      @tasks = current_user.tasks.order(created_at: :desc).page(params[:page])
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to task_path(@task.id), notice: "タスクを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority, { label_ids:[] } )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if @current_user.id != @user.id
      redirect_to tasks_path, notice: "権限がありません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end  
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <div class="user_form">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_form">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_form">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="user_form">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_form">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit "登録" %>
<% end %>

app/views/admin/users/edit.html.erb
<h2>ユーザー編集</h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
<p><%= notice %></p>
<%= link_to '新規作成', new_admin_user_path, class: "btn btn-primary" %>
<table>
  <tr>
    <th>ユーザー名</th>
    <th>メールアドレス</th>
    <th>管理権限</th>
    <th>登録日時</th>
    <th>更新日時</th>
    <th>タスク数</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin? ? 'あり' : 'なし' %></td>
      <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= user.updated_at.strftime('%Y-%m-%d') %></td>
      <td><%= user.tasks.count %>件</td>
      <td><%= link_to '詳細', [:admin, user], class: "btn btn-outline-primary" %></td>
      <td><%= link_to '編集', edit_admin_user_path(user), class: "btn btn-outline-success" %></td>
      <td><%= link_to '削除', [:admin, user], method: :delete ,data: { confirm: 'ユーザー「#{user.name}」を削除します。よろしいですか？」' }, class: "btn btn-outline-danger" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h2>ユーザー登録</h2>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>ユーザー詳細</h1>
<p>ID:<%= @user.id %></p>
<p>名前:<%= @user.name %></p>
<p>メールアドレス:<%= @user.email %></p>
<p>管理権限:<%= @user.admin? ? 'あり' : 'なし' %></p>
<p>作成日時:<%= @user.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
<p>更新日時:<%= @user.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
<%= link_to '編集', edit_admin_user_path(@user), class: "btn btn-outline-success" %>
<%= link_to '削除', [:admin, @user], method: :delete ,data: { confirm: 'ユーザー「#{@user.name}」を削除します。よろしいですか？」' }, class: "btn btn-outline-danger" %>
<%= link_to "戻る", admin_users_path %>

<table>
  <tr>
    <th>ユーザー名</th>
    <th>タスク名</th>
    <th>詳しい内容</th>
    <th>登録日時</th>
    <th><%= link_to "終了期限", tasks_path(sort_expired: "true") %></th>
    <th>ステータス</th>
    <th><%= link_to "優先順位", tasks_path(sort_priority: "true") %></th>
  </tr>
  <% @user.tasks.each do |task| %>
    <tr class="task_row">
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td><%= task.expired_at.strftime('%Y-%m-%d') %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to '詳細', task_path(task.id), class: "btn btn-outline-primary" %></td>
      <td><%= link_to '編集', edit_task_path(task.id), class: "btn btn-outline-success" %></td>
      <td><%= link_to '削除', task_path(task.id), class: "btn btn-outline-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "タスク一覧", tasks_path %>
      <% if current_user.admin? %>
        <%= link_to "ユーザー一覧", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="task">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="task">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>

  <div class="task">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys.map %>
  </div>

  <div class="task">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys.map %>
  </div>

  <div class="task">
    <%= form.label :label %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <%= form.submit "登録"%>
<% end %>
<%= link_to "戻る", tasks_path %>

app/views/tasks/confirm.html.erb
<h3>以下の内容で、登録する。</h3>

<%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :expired_at %>
  <%= form.hidden_field :status %>
  <%= form.hidden_field :priority %>
  <% @task.labels.each do |label| %> 
    <%= form.hidden_field :label_ids, multiple: true, value: label.id %> 
  <% end %> 

  <p>タイトル:<%= @task.title %></p>
  <p>本文:<%= @task.content %></p>
  <p>終了期限:<%= @task.expired_at.strftime('%Y-%m-%d') %></p>
  <p>ステータス:<%= @task.status %></p>
  <p>優先順位:<%= @task.priority %></p>
  <p>ラベル：
    <% @task.labels.each do |label| %>
      <%= label.name %>
    <% end %>
  </p>
  <%= form.submit "登録" %>

  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tasks/edit.html.erb
<h2>編集</h2>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= form_with( url: tasks_path, method: :get, scope: :task, local: true ) do |form| %>
  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <%= form.label :title, "タスク名", class: "form-label" %>
    </div>
    <div class="col-auto">
      <%= form.text_field :title, class: "form-control", placeholder: "検索..." %>
    </div>
    <div class="col-auto">
      <%= form.label :status, "ステータス", class: "form-label" %>
    </div>
    <div class="col-auto">
      <%= form.select :status, Task.statuses.keys, {include_blank: true}, class: 'form-control' %>
    </div>
    <div class="col-auto">
      <%= form.label :status, "ラベル", class: "form-label" %>
    </div>
    <div class="col-auto">
      <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }, class: 'form-control') %>
    </div>
    <%= form.submit "検索", class: "btn btn-outline-dark" %>
  </div>
<% end %>
<%= link_to '新規作成', new_task_path, class: "btn btn-primary" %>
<table>
  <tr>
    <th>ユーザー名</th>
    <th>タスク名</th>
    <th>詳しい内容</th>
    <th>登録日時</th>
    <th><%= link_to "終了期限", tasks_path(sort_expired: "true") %></th>
    <th>ステータス</th>
    <th><%= link_to "優先順位", tasks_path(sort_priority: "true") %></th>
  </tr>
  <% @tasks.each do |task| %>
    <tr class="task_row">
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
      <td><%= task.expired_at.strftime('%Y-%m-%d') %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to '詳細', task_path(task.id), class: "btn btn-outline-primary" %></td>
      <td><%= link_to '編集', edit_task_path(task.id), class: "btn btn-outline-success" %></td>
      <td><%= link_to '削除', task_path(task.id), class: "btn btn-outline-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>
<%= paginate(@tasks) %>

app/views/tasks/new.html.erb
<h2>新規作成</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>詳細</h1>
<p>タイトル:<%= @task.title %></p>
<p>内容:<%= @task.content %></p>
<p>終了期限:<%= @task.expired_at.strftime('%Y-%m-%d') %></p>
<p>ステータス:<%= @task.status %></p>
<p>優先順位:<%= @task.priority %></p>
<p>ラベル：
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>
<%= link_to "戻る", tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="user_form">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="user_form">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="user_form">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="user_form">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit "登録" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>